# Programación básica en TF

In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.1


### Tensores: Constantes y Variable



### Tensores constantes

* tf.constant()
* tf.zeros(),tf.ones() 
* tf.fill()
* tf.random


In [2]:
help(tf.constant)

Help on function constant in module tensorflow.python.framework.constant_op:

constant(value, dtype=None, shape=None, name='Const')
    Creates a constant tensor from a tensor-like object.
    
    Note: All eager `tf.Tensor` values are immutable (in contrast to
    `tf.Variable`). There is nothing especially _constant_ about the value
    returned from `tf.constant`. This function it is not fundamentally different
    from `tf.convert_to_tensor`. The name `tf.constant` comes from the symbolic
    APIs (like `tf.data` or keras functional models) where the `value` is embeded
    in a `Const` node in the `tf.Graph`. `tf.constant` is useful for asserting
    that the value can be embedded that way.
    
    If the argument `dtype` is not specified, then the type is inferred from
    the type of `value`.
    
    >>> # Constant 1-D Tensor from a python list.
    >>> tf.constant([1, 2, 3, 4, 5, 6])
    <tf.Tensor: shape=(6,), dtype=int32,
        numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)

In [3]:
const_a = tf.constant([[1,2,3,4]],shape=[2,2],dtype=tf.float32) # Una matriz de 2x2, con valores del 1 al 4

In [4]:
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [6]:
#Atributos comunes

print('Valor del tensor CONSTANTE', const_a.numpy())
print('Tipo de elementos', const_a.dtype)
print('Shape del tensor',const_a.shape)

Valor del tensor CONSTANTE [[1. 2.]
 [3. 4.]]
Tipo de elementos <dtype: 'float32'>
Shape del tensor (2, 2)


In [7]:
help(tf.zeros)

Help on function zeros in module tensorflow.python.ops.array_ops:

zeros(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to zero.
    
    See also `tf.zeros_like`, `tf.ones`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to zero.
    
    >>> tf.zeros([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: The DType of an element in the resulting `Tensor`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to zero.



In [8]:
zeros_b = tf.zeros([2,3]) #Matriz de 2x2, con todos los valores son 0

In [9]:
zeros_b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [10]:
ones_b = tf.ones([2,3])

In [11]:
ones_b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
help(tf.fill)

Help on function fill in module tensorflow.python.ops.array_ops:

fill(dims, value, name=None)
    Creates a tensor filled with a scalar value.
    
    See also `tf.ones`, `tf.zeros`, `tf.one_hot`, `tf.eye`.
    
    This operation creates a tensor of shape `dims` and fills it with `value`.
    
    For example:
    
    >>> tf.fill([2, 3], 9)
    <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
    array([[9, 9, 9],
           [9, 9, 9]], dtype=int32)>
    
    `tf.fill` evaluates at graph runtime and supports dynamic shapes based on
    other runtime `tf.Tensors`, unlike `tf.constant(value, shape=dims)`, which
    embeds the value as a `Const` node.
    
    Args:
      dims: A 1-D sequence of non-negative numbers. Represents the shape of the
        output `tf.Tensor`. Entries should be of type: `int32`, `int64`.
      value: A value to fill the returned `tf.Tensor`.
      name: Optional string. The name of the output `tf.Tensor`.
    
    Returns:
      A `tf.Tensor` with shape `dims

In [19]:
fill_d = tf.fill(dims=[3,3],value=8) #Matriz de 3x3, donde todos los valores son 8

# What's is the output of tf.fill(shape=[3,3],8)

1. <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
       
2. <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])>
       
3. Sintax error
       
       

In [16]:
fill_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])>

### tf.random 
* tf.random.uniform()
* tf.random.normal()
* tf.random.shuffle()

In [20]:
help(tf.random.normal)

Help on function random_normal in module tensorflow.python.ops.random_ops:

random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a normal distribution.
    
    Example that generates a new set of random values every time:
    
    >>> tf.random.set_seed(5);
    >>> tf.random.normal([4], 0, 1, tf.float32)
    <tf.Tensor: shape=(4,), dtype=float32, numpy=..., dtype=float32)>
    
    Example that outputs a reproducible result:
    
    >>> tf.random.set_seed(5);
    >>> tf.random.normal([2,2], 0, 1, tf.float32, seed=1)
    <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
    array([[-1.3768897 , -0.01258316],
          [-0.169515   ,  1.0824056 ]], dtype=float32)>
    
    In this case, we are setting both the global and operation-level seed to
    ensure this result is reproducible.  See `tf.random.set_seed` for more
    information.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tens

In [21]:
random_e = tf.random.normal([5,5],seed=1)

In [22]:
random_e

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

In [24]:
help(tf.convert_to_tensor)

Help on function convert_to_tensor_v2 in module tensorflow.python.framework.ops:

convert_to_tensor_v2(value, dtype=None, dtype_hint=None, name=None)
    Converts the given `value` to a `Tensor`.
    
    This function converts Python objects of various types to `Tensor`
    objects. It accepts `Tensor` objects, numpy arrays, Python lists,
    and Python scalars. For example:
    
    >>> def my_func(arg):
    ...   arg = tf.convert_to_tensor(arg, dtype=tf.float32)
    ...   return arg
    
    >>> # The following calls are equivalent.
    >>> value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
    >>> print(value_1)
    tf.Tensor(
      [[1. 2.]
       [3. 4.]], shape=(2, 2), dtype=float32)
    >>> value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
    >>> print(value_2)
    tf.Tensor(
      [[1. 2.]
       [3. 4.]], shape=(2, 2), dtype=float32)
    >>> value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))
    >>> print(value_3)
    tf.Tensor(
      [[1. 2.]
       [3.

In [25]:
listExample7 = [1,2,3,4,5,6]
type(listExample7)

list

In [27]:
list2tensor = tf.convert_to_tensor(listExample7,dtype=tf.float32)

In [29]:
list2tensor.numpy()

array([1., 2., 3., 4., 5., 6.], dtype=float32)

# Tensores variables 

tf.Variable

In [30]:
help(tf.Variable)

Help on class Variable in module tensorflow.python.ops.variables:

class Variable(tensorflow.python.training.tracking.base.Trackable)
 |  Variable(*args, **kwargs)
 |  
 |  See the [variable guide](https://tensorflow.org/guide/variable).
 |  
 |  A variable maintains shared, persistent state manipulated by a program.
 |  
 |  The `Variable()` constructor requires an initial value for the variable, which
 |  can be a `Tensor` of any type and shape. This initial value defines the type
 |  and shape of the variable. After construction, the type and shape of the
 |  variable are fixed. The value can be changed using one of the assign methods.
 |  
 |  >>> v = tf.Variable(1.)
 |  >>> v.assign(2.)
 |  <tf.Variable ... shape=() dtype=float32, numpy=2.0>
 |  >>> v.assign_add(0.5)
 |  <tf.Variable ... shape=() dtype=float32, numpy=2.5>
 |  
 |  The `shape` argument to `Variable`'s constructor allows you to construct a
 |  variable with a less defined shape than its `initial_value`:
 |  
 |  >>>

In [32]:
var_1 = tf.Variable(tf.ones([2,3]))
print(var_1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [33]:
print('Valor de la variable var_1', var_1.read_value())

Valor de la variable var_1 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [34]:
var_value_1 = [[1,2,3],[4,5,6]]
var_1.assign(var_value_1)
print('Valor de la variable var_1', var_1.read_value())

Valor de la variable var_1 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


## Slicing e Indexing de los tensores

## Slicing 
* [start:end] - Extrae desde la posición inicial hasta la posición final
* [start:end:step] o [::step] - Extrae en un intervalo de pasos
* [::-1] - Segmentación de datos del último elemento
* ...

In [35]:
tensor_h = tf.random.normal([4,100,100,3]) #4 imagenes, de tama;o 100x10 y son de color
print(tensor_h)

tf.Tensor(
[[[[-1.00054467e+00 -6.52104735e-01  1.09322834e+00]
   [ 9.87382114e-01  1.35380030e+00 -1.45619881e+00]
   [ 8.31169665e-01  2.27716357e-01  3.20754141e-01]
   ...
   [ 7.49929130e-01 -2.49788690e+00 -1.78810680e+00]
   [ 7.64013886e-01 -1.03356451e-01  5.81838667e-01]
   [ 1.22685242e+00  2.40965319e+00 -1.46277726e-01]]

  [[-2.62106627e-01  2.94600725e-02 -7.98700333e-01]
   [ 5.54642081e-01 -9.55811799e-01  6.64957762e-01]
   [-4.39755529e-01 -9.90762532e-01  1.20675361e+00]
   ...
   [ 1.29253447e-01  2.51268888e+00 -7.37603128e-01]
   [-1.56515932e+00 -1.23989537e-01 -1.04234195e+00]
   [-7.14586496e-01  5.78985333e-01 -5.27908504e-01]]

  [[ 5.92542887e-01 -3.80327851e-01  1.37927508e+00]
   [-2.84432173e-01 -1.15593277e-01 -2.15790415e+00]
   [ 9.94845152e-01 -4.68406528e-02  1.42201638e+00]
   ...
   [ 1.13928235e+00 -2.49847651e+00 -9.77994781e-03]
   [-1.41256678e+00  1.17498147e+00 -5.46238363e-01]
   [-9.96809065e-01  6.51917517e-01 -2.58832550e+00]]

  ...

 

In [36]:
#Extrayendo solo primera imagen

tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-1.0005447 , -0.65210474,  1.0932283 ],
        [ 0.9873821 ,  1.3538003 , -1.4561988 ],
        [ 0.83116966,  0.22771636,  0.32075414],
        ...,
        [ 0.74992913, -2.497887  , -1.7881068 ],
        [ 0.7640139 , -0.10335645,  0.58183867],
        [ 1.2268524 ,  2.4096532 , -0.14627773]],

       [[-0.26210663,  0.02946007, -0.79870033],
        [ 0.5546421 , -0.9558118 ,  0.66495776],
        [-0.43975553, -0.99076253,  1.2067536 ],
        ...,
        [ 0.12925345,  2.5126889 , -0.7376031 ],
        [-1.5651593 , -0.12398954, -1.042342  ],
        [-0.7145865 ,  0.57898533, -0.5279085 ]],

       [[ 0.5925429 , -0.38032785,  1.3792751 ],
        [-0.28443217, -0.11559328, -2.1579041 ],
        [ 0.99484515, -0.04684065,  1.4220164 ],
        ...,
        [ 1.1392823 , -2.4984765 , -0.00977995],
        [-1.4125668 ,  1.1749815 , -0.54623836],
        [-0.99680907,  0.6519175 , -2.5883255 ]],

       ...,

     

In [37]:
tensor_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.0005447 , -0.65210474,  1.0932283 ],
         [ 0.9873821 ,  1.3538003 , -1.4561988 ],
         [ 0.83116966,  0.22771636,  0.32075414],
         ...,
         [ 0.74992913, -2.497887  , -1.7881068 ],
         [ 0.7640139 , -0.10335645,  0.58183867],
         [ 1.2268524 ,  2.4096532 , -0.14627773]],

        [[-0.26210663,  0.02946007, -0.79870033],
         [ 0.5546421 , -0.9558118 ,  0.66495776],
         [-0.43975553, -0.99076253,  1.2067536 ],
         ...,
         [ 0.12925345,  2.5126889 , -0.7376031 ],
         [-1.5651593 , -0.12398954, -1.042342  ],
         [-0.7145865 ,  0.57898533, -0.5279085 ]],

        [[ 0.5925429 , -0.38032785,  1.3792751 ],
         [-0.28443217, -0.11559328, -2.1579041 ],
         [ 0.99484515, -0.04684065,  1.4220164 ],
         ...,
         [ 1.1392823 , -2.4984765 , -0.00977995],
         [-1.4125668 ,  1.1749815 , -0.54623836],
         [-0.99680907,  0.6519175 , -2.5883255

In [38]:
#Segmantando data del último elemento

tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.11900032e+00,  4.81359005e-01, -9.91551816e-01],
         [-1.63031006e+00,  1.72501713e-01,  8.15835357e-01],
         [ 1.59688011e-01,  1.33077705e+00,  4.56041634e-01],
         ...,
         [ 1.91381383e+00, -1.89852047e+00, -7.55266726e-01],
         [-2.84153819e-01,  1.40374526e-02,  4.47298065e-02],
         [ 6.09242141e-01,  7.61439949e-02, -2.10788584e+00]],

        [[ 7.35600114e-01,  4.78352547e-01,  8.96837592e-01],
         [ 6.47120416e-01, -1.09583867e+00, -1.19604361e+00],
         [ 6.66618526e-01,  3.98706526e-01,  1.80406556e-01],
         ...,
         [ 9.84750032e-01, -1.97311834e-01, -3.01506847e-01],
         [ 3.38715523e-01,  1.11628532e+00, -1.51822656e-01],
         [-9.46477413e-01, -2.10963264e-01,  9.68777716e-01]],

        [[ 1.57837355e+00,  1.85300782e-01,  8.10187340e-01],
         [ 1.51580572e+00, -2.78805941e-01, -1.61838102e+00],
         [ 1.27503676e-02, -6.05727971e-01

## Indexación

Formato básico es tensor[d1][d2][d3]......

In [39]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.8111355>

help(tf.gather)

In [42]:
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5546421, 0.5044609], dtype=float32)>

# Modificación de dimensiones

In [43]:
const_d_1 = tf.constant([[1,2,3,4]],shape=[2,2])
print(const_d_1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [44]:
#Maneras para devolver la dim

print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1)) #Ouput de este, es un tensor

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [45]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a new `tf.Tensor` that has the same
    values as `tensor` in the same order, except with a new shape given by
    `shape`.
    
    >>> t1 = [[1, 2, 3],
    ...       [4, 5, 6]]
    >>> print(tf.shape(t1).numpy())
    [2 3]
    >>> t2 = tf.reshape(t1, [6])
    >>> t2
    <tf.Tensor: shape=(6,), dtype=int32,
      numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
    >>> tf.reshape(t2, [3, 2])
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
      array([[1, 2],
             [3, 4],
             [5, 6]], dtype=int32)>
    
    The `tf.reshape` does not change the order of or the total number of elements
    in the tensor, and so it can reuse the underlying data buffer. This makes it
    a fast operation independent of how big of a tensor it is operating on.
    
    >>> tf.reshape([1, 2, 3], [2, 2])
    Traceback (mos

In [52]:
resphape_1 = tf.constant([[1,2,3],[4,5,6]])

In [57]:
resphape_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [55]:
resphape_1.shape

TensorShape([2, 3])

In [56]:
tf.reshape(resphape_1,(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [58]:
help(tf.expand_dims)

Help on function expand_dims_v2 in module tensorflow.python.ops.array_ops:

expand_dims_v2(input, axis, name=None)
    Returns a tensor with a length 1 axis inserted at index `axis`.
    
    Given a tensor `input`, this operation inserts a dimension of length 1 at the
    dimension index `axis` of `input`'s shape. The dimension index follows Python
    indexing rules: It's zero-based, a negative index it is counted backward
    from the end.
    
    This operation is useful to:
    
    * Add an outer "batch" dimension to a single element.
    * Align axes for broadcasting.
    * To add an inner vector length axis to a tensor of scalars.
    
    For example:
    
    If you have a single image of shape `[height, width, channels]`:
    
    >>> image = tf.zeros([10,10,3])
    
    You can add an outer `batch` axis by passing `axis=0`:
    
    >>> tf.expand_dims(image, axis=0).shape.as_list()
    [1, 10, 10, 3]
    
    The new axis location matches Python `list.insert(axis, 1)`:
   

In [59]:
expand_sample_1 = tf.random.normal([100,100,3])
print('Dimensiones originales',expand_sample_1.shape)

Dimensiones originales (100, 100, 3)


In [60]:
print('Agregando una dimension, antes de la primera dimension, (axis=0)', tf.expand_dims(expand_sample_1,axis=0).shape)

Agregando una dimension, antes de la primera dimension, (axis=0) (1, 100, 100, 3)


In [61]:
print('Agregando una dimension, antes de la segunda dimension, (axis=1)', tf.expand_dims(expand_sample_1,axis=1).shape)

Agregando una dimension, antes de la segunda dimension, (axis=1) (100, 1, 100, 3)


In [63]:
print('Agregando dimension, después de la ULTIMA dimensión (axis=-1)',tf.expand_dims(expand_sample_1,axis=-1).shape)

Agregando dimension, después de la ULTIMA dimensión (axis=-1) (100, 100, 3, 1)


# Squeezing

In [64]:
help(tf.squeeze)

Help on function squeeze_v2 in module tensorflow.python.ops.array_ops:

squeeze_v2(input, axis=None, name=None)
    Removes dimensions of size 1 from the shape of a tensor.
    
    Given a tensor `input`, this operation returns a tensor of the same type with
    all dimensions of size 1 removed. If you don't want to remove all size 1
    dimensions, you can remove specific size 1 dimensions by specifying
    `axis`.
    
    For example:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t))  # [2, 3]
    ```
    
    Or, to remove specific size 1 dimensions:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t, [2, 4]))  # [1, 2, 3, 1]
    ```
    
    Unlike the older op `tf.compat.v1.squeeze`, this op does not accept a
    deprecated `squeeze_dims` argument.
    
    Note: if `input` is a `tf.RaggedTensor`, then this operation takes `O(N)`
    time, where `N` is the number of elements in the squeeze

In [65]:
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print(squeeze_sample_1.shape)

(1, 100, 100, 3)


In [69]:
squeezed_sample_1 = tf.squeeze(squeeze_sample_1,axis=0)
print(squeezed_sample_1.shape)

(100, 100, 3)


#### Transponer

Se ocupa perm cuando hay varias dimensiones

In [70]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
    

In [71]:
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print('Dimn originales',trans_sample_1.shape)

Dimn originales (2, 3)


In [72]:
transposed_sample_1 = tf.transpose(trans_sample_1)
print('Dims transpuesta',transposed_sample_1.shape)

Dims transpuesta (3, 2)


In [73]:
trans_sample_2 = tf.random.normal([4,100,100,3])
print('Dimn originales',trans_sample_2.shape)

Dimn originales (4, 100, 100, 3)


In [76]:
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,3,1])
print('Dimn luego de transpuesta',transposed_sample_2.shape)

Dimn luego de transpuesta (4, 100, 3, 100)


# Broadcast 

In [77]:
help(tf.broadcast_to)

Help on function broadcast_to in module tensorflow.python.ops.gen_array_ops:

broadcast_to(input, shape, name=None)
    Broadcast an array for a compatible shape.
    
    Broadcasting is the process of making arrays to have compatible shapes
    for arithmetic operations. Two shapes are compatible if for each
    dimension pair they are either equal or one of them is one. When trying
    to broadcast a Tensor to a shape, it starts with the trailing dimensions,
    and works its way forward.
    
    For example,
    
    >>> x = tf.constant([1, 2, 3])
    >>> y = tf.broadcast_to(x, [3, 3])
    >>> print(y)
    tf.Tensor(
        [[1 2 3]
         [1 2 3]
         [1 2 3]], shape=(3, 3), dtype=int32)
    
    In the above example, the input Tensor with the shape of `[1, 3]`
    is broadcasted to output Tensor with shape of `[3, 3]`.
    
    When doing broadcasted operations such as multiplying a tensor
    by a scalar, broadcasting (usually) confers some time or space
    benefit, as 

In [78]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])


Dim original (6,)


In [82]:
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print('Dim broadcasted', broadcasted_sample_1.shape)
print(broadcasted_sample_1.numpy())

Dim broadcasted (4, 6)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [83]:
a = tf.constant([[0,0,0],
                [10,10,10],
                [20,20,20],
                [30,30,30]])

b = tf.constant([1,2,3])

In [84]:
print(a+b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


# Operaciones artimeticas

* Suma
* Resta
* Multuplicación
* Logartimo
* Exponente

In [85]:
a = tf.constant([[3,5],[4,8]])
b = tf.constant([[1,6],[2,9]])


print(tf.add(a,b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [86]:
print(tf.matmul(a,b))

tf.Tensor(
[[13 63]
 [20 96]], shape=(2, 2), dtype=int32)


In [87]:
help(tf.matmul)

Help on function matmul in module tensorflow.python.ops.math_ops:

matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
    Multiplies matrix `a` by matrix `b`, producing `a` * `b`.
    
    The inputs must, following any transpositions, be tensors of rank >= 2
    where the inner 2 dimensions specify valid matrix multiplication dimensions,
    and any further outer dimensions specify matching batch size.
    
    Both matrices must be of the same type. The supported types are:
    `float16`, `float32`, `float64`, `int32`, `complex64`, `complex128`.
    
    Either matrix can be transposed or adjointed (conjugated and transposed) on
    the fly by setting one of the corresponding flag to `True`. These are `False`
    by default.
    
    If one or both of the matrices contain a lot of zeros, a more efficient
    multiplication algorithm can be used by setting the corresponding
    `a_is_sparse` or `b_is_sp

### Recopilación estadística

* tf.reduce_min/max/mean: 
* tf.argmax()/tf.argmin() 
* tf.equal()
* tf.unique()

In [88]:
help(tf.argmax)

Help on function argmax_v2 in module tensorflow.python.ops.math_ops:

argmax_v2(input, axis=None, output_type=tf.int64, name=None)
    Returns the index with the largest value across axes of a tensor.
    
    In case of identity returns the smallest index.
    
    For example:
    
    >>> A = tf.constant([2, 20, 30, 3, 6])
    >>> tf.math.argmax(A)  # A[2] is maximum in tensor A
    <tf.Tensor: shape=(), dtype=int64, numpy=2>
    >>> B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
    ...                  [14, 45, 23, 5, 27]])
    >>> tf.math.argmax(B, 0)
    <tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>
    >>> tf.math.argmax(B, 1)
    <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>
    >>> C = tf.constant([0, 0, 0, 0])
    >>> tf.math.argmax(C) # Returns smallest index in case of ties
    <tf.Tensor: shape=(), dtype=int64, numpy=0>
    
    Args:
      input: A `Tensor`.
      axis: An integer, the axis to reduce across. Default to 0.
     

In [95]:
argmax_sample_1 = tf.constant([[7,2,3],[2,5,8],[7,10,9]])
print(argmax_sample_1.numpy())

[[ 7  2  3]
 [ 2  5  8]
 [ 7 10  9]]


# Operaciones aritméticas basadas en dimensiones

* tf.reduce_sum
* tf.reduce_prod
* tf.reduce_min 
* tf.reduce_max
* tf.reduce_mean
* tf.reduce_all (Y lógico)
* tf.reduce_any (O lógico)

In [97]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    entry in `axis`. If `keepdims` is true, the reduced dimensions
    are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
    >>> # x has a shape of (2, 3) (two rows and three columns):
    >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
    >>> x.numpy()
    array([[1, 1, 1],
           [1, 1, 1]], dtype=int32)
    >>> # sum all the elements
    >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
    >>> tf.reduce_sum(x).numpy()
    6
    >>> # reduce along the first dimension
    >>> # the result is [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
    >>> tf.reduce_sum(x, 

In [99]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print(reduce_sample_1.numpy())

[[1 2 3]
 [4 5 6]]


In [102]:
print('Calculando la suma a TODOS los elementos (axis=None)',tf.reduce_sum(reduce_sample_1,axis=None).numpy())

Calculando la suma a TODOS los elementos (axis=None) 21


In [103]:
print('Calculando por columna (axis=0)',tf.reduce_sum(reduce_sample_1,axis=0).numpy())

Calculando por columna (axis=0) [5 7 9]


In [104]:
print('Calculando por fila (axis=1)',tf.reduce_sum(reduce_sample_1,axis=1).numpy())

Calculando por fila (axis=1) [ 6 15]


# Contanenación - División

#### Concatenación:
* tf.concat 
* tf.stack 

In [105]:
help(tf.concat)

Help on function concat in module tensorflow.python.ops.array_ops:

concat(values, axis, name='concat')
    Concatenates tensors along one dimension.
    
    See also `tf.tile`, `tf.stack`, `tf.repeat`.
    
    Concatenates the list of tensors `values` along dimension `axis`.  If
    `values[i].shape = [D0, D1, ... Daxis(i), ...Dn]`, the concatenated
    result has shape
    
        [D0, D1, ... Raxis, ...Dn]
    
    where
    
        Raxis = sum(Daxis(i))
    
    That is, the data from the input tensors is joined along the `axis`
    dimension.
    
    The number of dimensions of the input tensors must match, and all dimensions
    except `axis` must be equal.
    
    For example:
    
    >>> t1 = [[1, 2, 3], [4, 5, 6]]
    >>> t2 = [[7, 8, 9], [10, 11, 12]]
    >>> tf.concat([t1, t2], 0)
    <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]], dtype=int32)>
    
    >>> tf.concat([t

In [106]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([4,100,100,3])

print('Dim originales',concat_sample_1.shape,concat_sample_2.shape)

Dim originales (4, 100, 100, 3) (4, 100, 100, 3)


In [109]:
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=3)
print('Dim del tensor concatenado',concated_sample_1.shape)

Dim del tensor concatenado (4, 100, 100, 6)


In [110]:
help(tf.stack)

Help on function stack in module tensorflow.python.ops.array_ops:

stack(values, axis=0, name='stack')
    Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor.
    
    See also `tf.concat`, `tf.tile`, `tf.repeat`.
    
    Packs the list of tensors in `values` into a tensor with rank one higher than
    each tensor in `values`, by packing them along the `axis` dimension.
    Given a list of length `N` of tensors of shape `(A, B, C)`;
    
    if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
    if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.
    Etc.
    
    For example:
    
    >>> x = tf.constant([1, 4])
    >>> y = tf.constant([2, 5])
    >>> z = tf.constant([3, 6])
    >>> tf.stack([x, y, z])
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
    array([[1, 4],
           [2, 5],
           [3, 6]], dtype=int32)>
    >>> tf.stack([x, y, z], axis=1)
    <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
    array([[1, 2,

In [111]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])

print('Dim originales',stack_sample_1.shape,stack_sample_2.shape)

Dim originales (100, 100, 3) (100, 100, 3)


In [112]:
stacked_sample_1 = tf.stack([stack_sample_1,stack_sample_2])
print('Dimn nueva',stacked_sample_1.shape)

Dimn nueva (2, 100, 100, 3)


## División de tensores 

* tf.unstack() - Divide un tensor por una dim especifica
* tf.split() 


In [113]:
help(tf.unstack)

Help on function unstack in module tensorflow.python.ops.array_ops:

unstack(value, num=None, axis=0, name='unstack')
    Unpacks the given dimension of a rank-`R` tensor into rank-`(R-1)` tensors.
    
    Unpacks `num` tensors from `value` by chipping it along the `axis` dimension.
    If `num` is not specified (the default), it is inferred from `value`'s shape.
    If `value.shape[axis]` is not known, `ValueError` is raised.
    
    For example, given a tensor of shape `(A, B, C, D)`;
    
    If `axis == 0` then the i'th tensor in `output` is the slice
      `value[i, :, :, :]` and each tensor in `output` will have shape `(B, C, D)`.
      (Note that the dimension unpacked along is gone, unlike `split`).
    
    If `axis == 1` then the i'th tensor in `output` is the slice
      `value[:, i, :, :]` and each tensor in `output` will have shape `(A, C, D)`.
    Etc.
    
    This is the opposite of stack.
    
    Args:
      value: A rank `R > 0` `Tensor` to be unstacked.
      num:

In [115]:
stacked_sample_1.shape

TensorShape([2, 100, 100, 3])

In [117]:
tf.unstack(stacked_sample_1,axis=0) 

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-1.62930727e+00, -1.91322780e+00, -2.73170531e-01],
         [ 1.09348404e+00,  4.64917213e-01,  8.57612610e-01],
         [ 1.13103867e+00,  7.25233376e-01,  1.01267493e+00],
         ...,
         [-2.00934625e+00,  7.82824099e-01,  2.82770824e-02],
         [ 5.13250411e-01,  9.47809160e-01,  2.11677905e-02],
         [ 5.31098068e-01,  2.21277744e-01,  1.83563590e-01]],
 
        [[ 7.78314531e-01, -1.64613080e+00, -5.36854267e-01],
         [-5.97901531e-02, -4.14725721e-01,  5.19917250e-01],
         [ 1.03787100e+00,  8.33033979e-01,  2.33838946e-01],
         ...,
         [ 6.48794353e-01, -1.70689070e+00,  9.60010827e-01],
         [-3.29141617e-01,  4.99220282e-01, -7.53772676e-01],
         [-7.54969537e-01,  8.64554644e-01,  8.69382083e-01]],
 
        [[ 1.18388367e+00, -9.84409451e-01,  6.05888784e-01],
         [ 1.02480459e+00, -9.02650692e-03,  1.58609793e-01],
         [ 7.81348348e-01,  7.35665739e-01

In [118]:
help(tf.split)

Help on function split in module tensorflow.python.ops.array_ops:

split(value, num_or_size_splits, axis=0, num=None, name='split')
    Splits a tensor `value` into a list of sub tensors.
    
    See also `tf.unstack`.
    
    If `num_or_size_splits` is an integer,  then `value` is split along the
    dimension `axis` into `num_or_size_splits` smaller tensors. This requires that
    `value.shape[axis]` is divisible by `num_or_size_splits`.
    
    If `num_or_size_splits` is a 1-D Tensor (or list), then `value` is split into
    `len(num_or_size_splits)` elements. The shape of the `i`-th
    element has the same size as the `value` except along dimension `axis` where
    the size is `num_or_size_splits[i]`.
    
    For example:
    
    >>> x = tf.Variable(tf.random.uniform([5, 30], -1, 1))
    >>>
    >>> # Split `x` into 3 tensors along dimension 1
    >>> s0, s1, s2 = tf.split(x, num_or_size_splits=3, axis=1)
    >>> tf.shape(s0).numpy()
    array([ 5, 10], dtype=int32)
    >>>
 

### Sobre el parametro num_or_size_splits

* entero, el tensor se divide UNIFORMEMENTE en subtensores en la dimensión que se le espeficique
* vector, el tensor se divide en subtensores segun el valor del elemento del VECTOR, en la dimensión especificada

In [122]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print('Dims originales', split_sample_1.shape)

Dims originales (10, 100, 100, 3)


In [123]:
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5)
print(np.shape(splited_sample_1))

(5, 2, 100, 100, 3)


In [125]:
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2])

print(np.shape(splited_sample_2[0]))
print(np.shape(splited_sample_2[1]))
print(np.shape(splited_sample_2[2]))

(3, 100, 100, 3)
(5, 100, 100, 3)
(2, 100, 100, 3)


### Sorting de tensores

* tf.sort()
* tf.argsort()

In [126]:
help(tf.sort)

Help on function sort in module tensorflow.python.ops.sort_ops:

sort(values, axis=-1, direction='ASCENDING', name=None)
    Sorts a tensor.
    
    Usage:
    
    ```python
    import tensorflow as tf
    a = [1, 10, 26.9, 2.8, 166.32, 62.3]
    b = tf.sort(a,axis=-1,direction='ASCENDING',name=None)
    c = tf.keras.backend.eval(b)
    # Here, c = [  1.     2.8   10.    26.9   62.3  166.32]
    ```
    
    Args:
      values: 1-D or higher numeric `Tensor`.
      axis: The axis along which to sort. The default is -1, which sorts the last
        axis.
      direction: The direction in which to sort the values (`'ASCENDING'` or
        `'DESCENDING'`).
      name: Optional name for the operation.
    
    Returns:
      A `Tensor` with the same dtype and shape as `values`, with the elements
          sorted along the given `axis`.
    
    Raises:
      ValueError: If axis is not a constant scalar, or the direction is invalid.



In [129]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [131]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print(sort_sample_1.numpy())

[8 7 6 5 0 4 9 2 3 1]


In [135]:
sorted_sample_1 = tf.sort(sort_sample_1,direction='DESCENDING')
print(sorted_sample_1.numpy())

[9 8 7 6 5 4 3 2 1 0]
